In [83]:
import pandas as pd
import numpy as np

In [99]:
df = pd.read_csv('./data/train_data.csv', low_memory=False)

In [19]:
df

,Unnamed: 0,Id,OpportunityId,CreatedById,CreatedDate,CreatedDateForInsert,StageName,Amount,Probability,PrevOpportunityStageUpdate,...,SCC_Interest__c,Company_s_CRM_Type__c,Deal_type__c,Needs__c,Type_of_Users__c,TAM__c,Secondary_CSM__c,Source_Type__c,Original_Lead_Source__c,Original_Lead_Source_Details__c
0,0,0081300002NRVGwAAP,00613000019fCVIAA2,00530000004M1PmAAK,6/30/2014 15:21,6/30/2014 15:21,0% probability Closed Lost,0.0,100,6/30/2014 15:21,...,0,NaN,NaN,NaN,NaN,0051B000009NLbeQAG,0051B00000CsqZ4QAJ,NaN,Inbound,Marketplace - SFDC AppExchange
1,1,0081300002OmHzxAAF,0061300001AAxCTAA1,00530000004M1PmAAK,8/27/2014 20:42,8/27/2014 20:42,100% Won / PO / Invoiced,14250.0,100,8/27/2014 20:42,...,0,Salesforce,NaN,NaN,NaN,0051300000C41JZAAZ,0051B000009MC2dQAG,NaN,Inbound,Marketplace - SFDC AppExchange
2,2,0081300002OmI2DAAV,0061300001AAxCTAA1,00530000004M1PmAAK,8/27/2014 20:42,8/27/2014 20:43,100% Won / PO / Invoiced,14250.0,30,8/27/2014 20:42,...,0,Salesforce,NaN,NaN,NaN,0051300000C41JZAAZ,0051B000009MC2dQAG,NaN,Inbound,Marketplace - SFDC AppExchange
3,3,0081300002OpToDAAV,0061300001ABzUgAAL,0051300000BAV3KAAX,9/22/2014 20:22,9/22/2014 20:22,100% Won / PO / Invoiced,4320.0,10,9/22/2014 20:22,...,0,Salesforce,NaN,User Adoption;User Productivity;Accessing CRM ...,Inside Sales,0051300000C41JZAAZ,0051B000009NLbZQAW,App Exchange,Inbound,Website Trial SignUp
4,4,0081300002OpYTKAA3,0061300001AC0orAAD,0051300000BAV3KAAX,9/23/2014 12:13,9/23/2014 12:13,0% probability Closed Expired,14250.0,10,9/23/2014 12:13,...,0,Salesforce,NaN,User Adoption;User Productivity;Accessing CRM ...,Field Sales,0051300000C41JZAAZ,0051B000009NLbZQAW,Website,Inbound,Website Contact Request
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34217,40990,008a000001t3lLuAAI,006a000000xh25QAAQ,00530000004M1PmAAK,1/11/2013 21:59,1/15/2013 17:32,0% probability Closed Lost,3000.0,50,1/11/2013 21:59,...,0,NaN,NaN,NaN,NaN,0051300000C41JZAAZ,0051B000009NLbZQAW,NaN,Inbound,Marketplace - SFDC AppExchange
34218,40991,008a000001t5F8AAAU,006a000000xiGgxAAE,00530000004M1PmAAK,1/18/2013 15:39,1/18/2013 15:39,0% probability Closed Lost,5000.0,100,1/18/2013 15:39,...,0,NaN,NaN,NaN,NaN,0051B000009NLbeQAG,0051B00000CsqZ4QAJ,NaN,Inbound,Marketplace - SFDC AppExchange
34219,40992,008a000001t5F9DAAU,006a000000xiGgxAAE,00530000004M1PmAAK,1/18/2013 15:39,1/18/2013 15:40,0% probability Closed Lost,5000.0,30,1/18/2013 15:39,...,0,NaN,NaN,NaN,NaN,0051B000009NLbeQAG,0051B00000CsqZ4QAJ,NaN,Inbound,Marketplace - SFDC AppExchange
34220,40993,008a000001t5FGiAAM,006a000000xiGkGAAU,00530000004M1PmAAK,1/18/2013 15:43,1/18/2013 15:43,0% probability Closed Lost,12000.0,70,1/18/2013 15:43,...,0,NaN,NaN,NaN,NaN,0051B000009NLbeQAG,0051B00000CsqZ4QAJ,NaN,NaN,NaN
34221,40994,008a000001t5GlOAAU,006a000000xiHMoAAM,00530000004M1PmAAK,1/18/2013 16:26,1/18/2013 16:26,0% probability Closed Lost,20000.0,30,1/18/2013 16:26,...,0,NaN,NaN,NaN,NaN,0051B000009NLbeQAG,0051B00000CsqZ4QAJ,NaN,NaN,NaN

In [122]:
some = df[df['OpportunityId'] == '0061300001AAxCTAA1']
some = some[['OpportunityId', 'CreatedDateForInsert', 'PrevOpportunityStageUpdate', 'Amount', 'StageName', 'Probability']]
some['CreatedDateForInsert'] = pd.to_datetime(some['CreatedDateForInsert'],format='%m/%d/%Y %H:%M')
some['PrevOpportunityStageUpdate'] = pd.to_datetime(some['PrevOpportunityStageUpdate'],format='%m/%d/%Y %H:%M')
# tmp = tmp.groupby('date', as_index=False).agg({'electricity': 'sum'})

some = some.sort_values(by=['CreatedDateForInsert'])
some

,OpportunityId,CreatedDateForInsert,PrevOpportunityStageUpdate,Amount,StageName,Probability
1,0061300001AAxCTAA1,2014-08-27 20:42:00,2014-08-27 20:42:00,14250.0,100% Won / PO / Invoiced,100
2,0061300001AAxCTAA1,2014-08-27 20:43:00,2014-08-27 20:42:00,14250.0,100% Won / PO / Invoiced,30
27,0061300001AAxCTAA1,2014-09-26 17:12:00,2014-08-27 20:43:00,14250.0,100% Won / PO / Invoiced,0
606,0061300001AAxCTAA1,2014-09-30 15:05:00,2014-09-26 17:12:00,14250.0,100% Won / PO / Invoiced,70
610,0061300001AAxCTAA1,2014-10-01 19:57:00,2014-09-30 15:05:00,14250.0,100% Won / PO / Invoiced,70
671,0061300001AAxCTAA1,2014-10-20 20:21:00,2014-09-30 15:05:00,14250.0,100% Won / PO / Invoiced,50
674,0061300001AAxCTAA1,2014-10-20 20:35:00,2014-10-20 20:21:00,14250.0,100% Won / PO / Invoiced,70
689,0061300001AAxCTAA1,2014-10-21 18:58:00,2014-10-20 20:35:00,14250.0,100% Won / PO / Invoiced,1
766,0061300001AAxCTAA1,2014-10-31 16:39:00,2014-10-21 18:58:00,14250.0,100% Won / PO / Invoiced,60
784,0061300001AAxCTAA1,2014-11-04 17:53:00,2014-10-31 16:39:00,14250.0,100% Won / PO / Invoiced,60
854,0061300001AAxCTAA1,2014-11-14 14:03:00,2014-10-31 16:39:00,14250.0,100% Won / PO / Invoiced,60
917,0061300001AAxCTAA1,2014-11-19 21:52:00,2014-10-31 16:39:00,14250.0,100% Won / PO / Invoiced,60
1000,0061300001AAxCTAA1,2014-12-05 14:39:00,2014-10-31 16:39:00,14250.0,100% Won / PO / Invoiced,60
1041,0061300001AAxCTAA1,2014-12-09 16:51:00,2014-10-31 16:39:00,14250.0,100% Won / PO / Invoiced,75
1141,0061300001AAxCTAA1,2014-12-30 15:48:00,2014-12-09 16:51:00,14250.0,100% Won / PO / Invoiced,75
1160,0061300001AAxCTAA1,2015-01-05 20:30:00,2014-12-09 16:51:00,14250.0,100% Won / PO / Invoiced,100

In [115]:
my = df[['OpportunityId', 'CreatedDateForInsert', 'StageName', 'Probability']]
my['CreatedDateForInsert'] = pd.to_datetime(my['CreatedDateForInsert'],format='%m/%d/%Y %H:%M')
my = my.sort_values(by=['CreatedDateForInsert'])
# my = my.groupby('OpportunityId')['Probability'].apply(list)

my = my.drop('CreatedDateForInsert', 1)
my = my.groupby('OpportunityId').agg(list)
my['StageName'] = my['StageName'].apply(lambda x : x[0])

# my = my.groupby('OpportunityId')[['StageName', 'Probability']].first()
# my = my.groupby('OpportunityId')[['StageName', 'Probability']]\
#         .apply(lambda x: x[['StageName','StageName']].values.tolist())\
#         .reset_index(name='col')
# my['Probability'] = my['Probability'][0]

/usr/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [116]:
my

,StageName,Probability
OpportunityId,,
00613000019fCVIAA2,0% probability Closed Lost,"[100, 0]"
0061300001AAxCTAA1,100% Won / PO / Invoiced,"[100, 30, 0, 70, 70, 50, 70, 1, 60, 60, 60, 60..."
0061300001ABzUgAAL,100% Won / PO / Invoiced,"[10, 30, 30, 30, 40, 40, 40, 40, 40, 90, 40, 9..."
0061300001AC0orAAD,0% probability Closed Expired,"[10, 30, 30, 30, 30, 40, 0, 1, 1, 0, 0, 0]"
0061300001AC0pGAAT,0% probability Closed Expired,"[10, 30, 30, 30, 40, 0, 1, 0, 0, 0]"
...,...,...
006a000000xh25QAAQ,0% probability Closed Lost,"[100, 50, 0]"
006a000000xhhIZAAY,0% probability Closed Lost,"[30, 0]"
006a000000xiGgxAAE,0% probability Closed Lost,"[100, 30, 0]"
006a000000xiGkGAAU,0% probability Closed Lost,"[70, 0]"
006a000000xiHMoAAM,0% probability Closed Lost,"[30, 0]"

In [121]:
y = []
X = []
numX = 4

for lst in my['Probability']:
    if len(lst) < numX+1:
        continue
    for i in range(0, len(lst)-numX):
        y.append(lst[i+numX])
        X.append([lst[i+j] for j in range(numX)])
        

y = np.array(y)
X = np.array(X)

print(X.shape)
print(y.shape)

(11542, 4)
(11542,)